# Generated by Django 5.0 on 2023-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameFactory', models.CharField(max_length=255, verbose_name='Наименование предприятия')),
                ('CostWorkshopId1', models.IntegerField(verbose_name='Цена 1-ой мастерской')),
                ('CostWorkshopId2', models.IntegerField(verbose_name='Цена 2-ой мастерской')),
                ('CostWorkshopId3', models.IntegerField(verbose_name='Цена 3-ей мастерской')),
                ('CostWorkshopId4', models.IntegerField(verbose_name='Цена 4-ой мастерской')),
                ('PowerFactory', models.IntegerField(verbose_name='Мощность предприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Ogranichenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SumWorkshopId1', models.IntegerField(verbose_name='Сумма 1-ой мастерской')),
                ('SumWorkshopId2', models.IntegerField(verbose_name='Сумма 2-ой мастерской')),
                ('SumWorkshopId3', models.IntegerField(verbose_name='Сумма 3-ей мастерской')),
                ('SumWorkshopId4', models.IntegerField(verbose_name='Сумма 4-ой мастерской')),
            ],
        ),
        migrations.CreateModel(
            name='OutputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameFactory', models.TextField(verbose_name='Наименование предприятия')),
                ('CostWorkshopId1', models.IntegerField(verbose_name='Цена 1-ой мастерской')),
                ('CostWorkshopId2', models.IntegerField(verbose_name='Цена 2-ой мастерской')),
                ('CostWorkshopId3', models.IntegerField(verbose_name='Цена 3-ей мастерской')),
                ('CostWorkshopId4', models.IntegerField(verbose_name='Цена 4-ой мастерской')),
                ('PowerFactory', models.IntegerField(verbose_name='Мощность предприятия')),
            ],
        ),
    ]
